[theme]
name = "catppuccin"
auto_switch = false

[ui]
show_agent_labels_on_pane_borders = true
agent_panel_sort = "spaces"
sidebar_collapsed_mode = "hidden"
pane_borders = true
hide_tab_bar_when_single_tab = true

[ui.toast]
delivery = "herdr"

[ui.toast.herdr]
position = "top-right"


[ui.sidebar.agents]
rows = [["state_icon", "workspace"], ["pane"]]

[ui.sidebar.spaces]
rows = [["workspace"], ["branch", "git_status"]]
